// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"time"

	"github.com/gofrs/uuid"
)

type Order struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	PaymentID uuid.UUID
	Price     float64
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
