/*
 * Billing service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"net/http"

	"billing-service/internal/billing"

	"github.com/gofrs/uuid"
)

// BillingApiService is a service that implents the logic for the BillingApiServicer
// This service should implement the business logic for every endpoint for the BillingApi API.
// Include any external packages or services that will be required by this service.
type BillingApiService struct {
	accounts billing.AccountRepository
}

// NewBillingApiService creates a default api service
func NewBillingApiService(accounts billing.AccountRepository) BillingApiServicer {
	return &BillingApiService{accounts: accounts}
}

// GetBillingAccount -
func (s *BillingApiService) GetBillingAccount(ctx context.Context, id uuid.UUID) (ImplResponse, error) {
	account, err := s.accounts.FindByID(ctx, id)
	if err != nil {
		return Response(http.StatusInternalServerError, nil), err
	}

	return Response(http.StatusOK, account), nil
}

// DepositMoney -
func (s *BillingApiService) DepositMoney(ctx context.Context, form AccountUpdateForm) (ImplResponse, error) {
	account, err := s.accounts.FindByID(ctx, form.ID)
	if err != nil {
		return Response(http.StatusInternalServerError, nil), err
	}

	account.Amount += form.Amount

	err = s.accounts.Save(ctx, account)
	if err != nil {
		return Response(http.StatusInternalServerError, nil), err
	}

	return Response(http.StatusNoContent, nil), nil
}

// WithdrawMoney -
func (s *BillingApiService) WithdrawMoney(ctx context.Context, form AccountUpdateForm) (ImplResponse, error) {
	account, err := s.accounts.FindByID(ctx, form.ID)
	if err != nil {
		return Response(http.StatusInternalServerError, nil), err
	}

	account.Amount -= form.Amount
	if account.Amount < 0 {
		return Response(http.StatusUnprocessableEntity, Error{
			Code:    http.StatusUnprocessableEntity,
			Message: "Not enough money on the account",
		}), nil
	}

	err = s.accounts.Save(ctx, account)
	if err != nil {
		return Response(http.StatusInternalServerError, nil), err
	}

	return Response(http.StatusNoContent, nil), nil
}
